### ISSUE TITLE
Train/test scripts 

### ISSUE THREAD

**Issue by xiaomengyc** [shelhamer/revolver#1]
Hi, 

Can you share the training/testing scripts and settings for reproducing the results in ICLR workshop paper?

**Comment by zhukaii** [comment]
Hi，
I'm reproducing the results with the model 'late-conditional-class' and the dataset 'sbdd', but there is something wrong with the results. 
Is my parameter setting correct?

**Comment by shelhamer** [comment]
The training and evaluation scripts for interactive segmentation and semantic segmentation are now included in https://github.com/shelhamer/revolver/commit/74610bf582fbb9295f21c4bbc10e49b826c35c8a.

Thank you for your interest in our method, and sorry for the wait!
