### ISSUE TITLE
Questions about evaluate.py

### ISSUE THREAD

**Issue by DL-Alva** [shelhamer/revolver#5]
Hi, I'm trying to run evaluate.py.However, I'm confused the meaning of parameter "experiment". Waiting for your reply and thank you so much.

**Comment by shelhamer** [comment]
The `experiment` argument is an identifier for the user to identify an experimental run. It is first set by training https://github.com/shelhamer/revolver/blob/master/train.py#L35 and then evaluation should take the same argument to evaluate that training experiment.

That is, you might do an experiment with interactive segmentation on PASCAL VOC and set the `experiment` argument to something like "interactive-voc-my-summary-here" and then when it comes time to call `evaluate.py` give the same argument.
